import React, { useState, useEffect } from 'react';
import ReportTable from './ReportTable';
import defaultData from './data.json';
import './index.css';

function App() {
  const [reportData, setReportData] = useState(null);

  useEffect(() => {
    const jsonUrl = import.meta.env.VITE_JSON_URL || '/results.json'; 
    
    fetch(jsonUrl)
      .then(response => {
        if (!response.ok) {
          throw new Error('Failed to fetch data');
        }
        return response.json();
      })
      .then(data => setReportData(data))
      .catch(error => {
        console.error('Error:', error);
        setReportData(defaultData);
      });
  }, []);

  return (
    <div className="app-container">
      <header className="app-header">
        <h1>NetScalpel — Network Report</h1>
      </header>
      
      <main className="app-main">
        {reportData ? (
          <ReportTable data={reportData} />
        ) : (
          <div className="loading">Loading data...</div>
        )}
      </main>
      
      <footer className="app-footer">
        <p>Generated by NetScalpel &copy; {new Date().getFullYear()}</p>
        <p style={{ fontSize: '0.75rem', opacity: 0.5, marginTop: '6px' }}>
          created by Haider Bassem &nbsp;|&nbsp; 
          <a href="https://www.linkedin.com/in/haiderbassem1/" target="_blank" rel="noreferrer" style={{ color: 'inherit', textDecoration: 'none' }}> LinkedIn</a>
          &nbsp;|&nbsp;
          <a href="https://github.com/haiderbassem" target="_blank" rel="noreferrer" style={{ color: 'inherit', textDecoration: 'none' }}> GitHub</a>
        </p>
      </footer>
    </div>
  );
}

export default App;
